postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *postgresql
  database: club_west_api_development

test:
  <<: *postgresql
  database: club_west_api_test

production:
  <<: *postgresql
  database: club_west_api_production
  username: club_west_api
  password: <%= ENV["CLUB_WEST_API_DATABASE_PASSWORD"] %>

