postgresql: &postgresql
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000


development:
  <<: *postgresql
  database: club-west-api_development

test:
  <<: *postgresql
  database: club-west-api_test

production:
  <<: *postgresql
  database: club-west-api_production