postgresql: &postgresql
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000


development:
  <<: *postgresql
  database: club_west_api_development

test:
  <<: *postgresql
  database: club_west_api_test

production:
  <<: *postgresql
  database: club_west_api_production